buildscript {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
    }
    dependencies {
        classpath "net.fabricmc:fabric-loom:${loom_version}"
    }
}

apply plugin: 'fabric-loom'

rootProject.ext.loadModProperties(project, 'TS_SpacetimeTraverse')

dependencies {
    compileOnly project(path: ':TokorotenSlime:common', configuration: 'namedElements')

     compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
}
