buildscript {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
    }
    dependencies {
        classpath "net.fabricmc:fabric-loom:${loom_version}"
    }
}

apply plugin: 'fabric-loom'

// このmod(TS_SpacetimeTraverse)配下のcommon/forge/fabricで共有するプロパティ(mod_id等)を読み込む。
rootProject.ext.loadModProperties(project, 'TS_SpacetimeTraverse')

dependencies {
    // TokorotenSlime(コアMod)commonへの依存。TokorotenSlimeClientAPI/TokorotenSlimeCommon.MOD_ID等を参照するため。
    compileOnly project(path: ':TokorotenSlime:common', configuration: 'namedElements')

     compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
}
