plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

rootProject.ext.loadModProperties(project, 'TS_SpacetimeTraverse')

rootProject.ext.configureCommonModule(project)

dependencies {
    compileOnly project(':TokorotenSlime:common')
}

configurations.runtimeClasspath {
    exclude group: 'net.minecraft'
}
