license="${mod_license}"
issueTrackerURL="https://github.com/kasaradanamo/TS-SpacetimeTraverse/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/ts-spacetime-traverse"
iconFile="icon.png"
authors="${mod_authors}"
description="${mod_description}"

[[mixins]]
config="ts_spacetime_traverse.neoforge.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tokorotenslime"
    type="required"
    versionRange="[${tokorotenslime_version},)"
    ordering="NONE"
    side="BOTH"
